[package]
name = "Lean-tutorials"
version = "0.1"
lean_version = "leanprover-community/lean:3.23.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "9dd9b6b07c27e971c8d24413d4fdb653fc7b3a67"}
Shannon-theory = {git = "https://github.com/BassemSafieldeen/Shannon-theory", rev = "138f671d14f34fa5886c9b13b1a64cb1783efe07"}
